<h1>Personen</h1>


<table class="table">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Geburtstag</th>
        <th scope="col">Gehalt</th>
        <th class="ms-auto"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->persons as $person): ?>
    <tr>
        <td>
            <?= $this->escapeHtml($person->getFullName()) ?>
        </td>
        <td>
            <?= $this->escapeHtml($person->getBirthday()) ?>
        </td>
        <td>
            <?= $this->escapeHtml($person->getSalary()) ?>
        </td>
        <td class="flex-row justify-content-end d-flex gap-1">
            <a type="button" class="btn btn-dark" href="<?= $this->url("person/edit", [
                "id" => $person->getId(),
            ]) ?>">Edit</a>
            <a type="button" class="btn btn-danger" href="<?= $this->url("person/delete", [
                "id" => $person->getId(),
            ]) ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>